platform :ios, '9.0'

use_frameworks!

pod 'google-cast-sdk'
#pod 'VigourCore', :path => '/Development/Clients/Vigour.io/vigour-native/native/ios/VigourCore'
pod 'VigourCore', :git => 'https://github.com/vigour-io/wrapper.git', :branch => 'feature/core-framework'